name: Split Monorepo

on:
  push:
    branches:
      - main  # Trigger when there's a push to the main branch

jobs:
  split_apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create and push platform branch
        run: |
          git switch --orphan platform
          git checkout main -- /apps/platform
          git add .
          git commit -m "Move platform to root"
          git push -f "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/joshimello/revuwr.git" platform

      - name: Create and push admin branch
        run: |
          git switch --orphan admin
          git checkout main -- /apps/admin
          git add .
          git commit -m "Move admin to root"
          git push -f "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/joshimello/revuwr.git" admin
