name: Split Monorepo

on:
  push:
    branches:
      - main  # Trigger when there's a push to the main branch

jobs:
  split_apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create and push platform branch
        run: |
          # Create a new branch for platform
          git checkout --orphan platform
          # Remove all files
          git rm -rf .
          # Copy /apps/platform to root
          cp -r apps/platform/* .
          # Add, commit, and push changes to the platform branch
          git add .
          git commit -m "Move platform to root"
          git push -f "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/joshimello/revuwr.git" platform

      - name: Create and push admin branch
        run: |
          # Create a new branch for admin
          git checkout --orphan admin
          # Remove all files
          git rm -rf .
          # Copy /apps/admin to root
          cp -r apps/admin/* .
          # Add, commit, and push changes to the admin branch
          git add .
          git commit -m "Move admin to root"
          git push -f "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/joshimello/revuwr.git" admin
